// Code generated by generate.py. DO NOT EDIT.

package sasstable

import "encoding/binary"

// DecodeMnemonic extracts the base SASS mnemonic from a 16-byte instruction
// word. archSM is the SM version number (e.g. 75, 80, 90). Returns "" if
// the opcode is unknown or the architecture is unsupported.
func DecodeMnemonic(archSM int, instrBytes [16]byte) string {
	table := ArchTables[archSM]
	if table == nil {
		return ""
	}
	// The opcode is in bits [0:11] of the lower 64-bit word (little-endian).
	lo := binary.LittleEndian.Uint64(instrBytes[0:8])
	opcode := uint16(lo & opcodeMask)
	return table[opcode]
}

// DecodeMnemonicFromSlice is a convenience wrapper that accepts a byte slice.
func DecodeMnemonicFromSlice(archSM int, instr []byte) string {
	if len(instr) < 16 {
		return ""
	}
	var buf [16]byte
	copy(buf[:], instr[:16])
	return DecodeMnemonic(archSM, buf)
}
